enthought/sat-solver

- LICENSE.txt
Add standard 3-clause BSD license.
> MAINT: Add license.

- .travis.yml
- simplesat/examples/van_der_waerden.py
- simplesat/sat/clause.py
- simplesat/sat/minisat.py
- simplesat/sat/policy.py
- simplesat/sat/tests/test_minisat.py
- tox.ini
> MAINT: test suite passes on python 3.

- simplesat/tests/crash.yaml
- simplesat/tests/test_scenarios_policy.py
> TST: add test showing broken case.

- .travis.yml
- dev_requirements.txt
- requirements_tests.txt
- setup.py
- tox.ini
> MAINT: consolidate test setup for travis/tox.

- simplesat/tests/ipython_downgrade.yaml
- simplesat/tests/ipython_upgrade.yaml
- simplesat/tests/ipython_virgin.yaml
- simplesat/tests/numpy_downgrade.yaml
- simplesat/tests/numpy_upgrade.yaml
- simplesat/tests/numpy_virgin.yaml
- simplesat/tests/scipy_downgrade.yaml
- simplesat/tests/scipy_upgrade.yaml
- simplesat/tests/scipy_virgin.yaml
> TST: add more test scenarios.

- README.rst
@cournape 
I would have preferred not reverting to plain ASCII for the names of the Minisat authors, but I don't know if there is a standard encoding we may assume...
> MAINT: Add bibliography.

- simplesat/tests/epd_full_upgrade.yaml
> TST: add epd full upgrade scenario.

- simplesat/sat/assignment_set.py
- simplesat/sat/clause.py
- simplesat/sat/minisat.py
- simplesat/sat/tests/test_assignment_set.py
- simplesat/sat/tests/test_minisat.py
- simplesat/sat/tests/test_minisat_problems.py
- simplesat/sat/utils.py
This is half of #55 and introduces the `AssignmentSet` along with its tests. The class functions as a drop-in replacement for `OrderedDict`, but is equipped with some extra methods for tracking changes to the values and validating input.
> Use a smart AssignmentSet class to track variable values

- scripts/solve.py
- setup.py
- simplesat/dependency_solver.py
- simplesat/utils/__init__.py
- simplesat/utils/timed_context.py
I found myself reimplementing this constantly. Since the solve script is already dumping everything on stdout, outputting the solving time to stderr seems reasonable to me.
> ENH: show dep solver running time in solve script

- .travis.yml
- setup.py
- simplesat/dependency_solver.py
- simplesat/tests/test_solver.py
- simplesat/transaction.py
- tox.ini
> ENH: add support for multiple operations in a request.

- scripts/print_rules.py
- scripts/scenario_to_php.py
- scripts/solve.py
- simplesat/test_utils.py
- simplesat/tests/test_scenarios_policy.py
- simplesat/tests/test_test_utils.py
@johntyree should remove any reference from `enstaller.new_solver.yaml_utils`. I also backported the tests and one feature from the code in enstaller.
> Consolidate scenario

- scripts/solve.py
- simplesat/dependency_solver.py
- simplesat/utils/timed_context.py
Now we time rule generation, SAT solver initialization, and problem solving separately.
> More granular timings

- simplesat/dependency_solver.py
- simplesat/tests/multiple_jobs.yaml
- simplesat/tests/test_scenarios_policy.py
A very stupid bug. :sob: 
Now we properly gather up all the requirement ids from *each* job and return those.
> Properly support multiple jobs

- simplesat/test_utils.py
- simplesat/tests/test_scenarios_policy.py
It was getting very tedious to iterate on failed tests.
Now it is less so.
> Show detailed diff in failed Scenario test output

- requirements.txt
- simplesat/dependency_solver.py
- simplesat/rules_generator.py
- simplesat/tests/simple_update_single.yaml
- simplesat/tests/test_scenarios_policy.py
- simplesat/tests/update_single.yaml
Remake of #87.
This PR adds support for "update" requests for single packages and provides some test scenarios for it.
The behavior is equivalent to explicitly requesting to install the latest version of the package that is being updated.
> Add support for package update requests.

- scripts/index_to_yaml.py
> BUG: fix index_to_yaml script for new enstaller.

- simplesat/rules_generator.py
I believe this to be the root of the problem.
Closes #96.
> BUG: deterministically iterate over package dependencies

- CHANGES.rst
@cournape
More detail? Less detail?
> DOC: create initial changelog. Changes for 0.1.0

- .gitignore
- setup.py
- simplesat/pool.py
- simplesat/test_data/__init__.py
- simplesat/test_data/indices/numpy_index.json
- simplesat/test_utils.py
- simplesat/tests/test_pool.py
- simplesat/tests/test_scenarios_policy.py
- simplesat/tests/test_solver.py
- simplesat/utils/__init__.py
- simplesat/utils/_collections.py
- simplesat/utils/tests/test_collections.py
This migrates the Pool from `enstaller.new_solver` into `simplesat` (should be merged after `maintenance/0.1.x` branch is cut)
> Move pool into sat

- simplesat/__init__.py
- simplesat/dependency_solver.py
- simplesat/errors.py
- simplesat/requirement.py
- simplesat/rules_generator.py
- simplesat/test_utils.py
- simplesat/tests/test_pool.py
- simplesat/tests/test_requirement.py
- simplesat/tests/test_solver.py
- simplesat/tests/test_test_utils.py
- simplesat/transaction.py
- simplesat/utils/_composer_utils.py
Built on top of #94 , so should be merged after
> REF: move Requirement from enstaller into simplesat.

- CHANGES.rst
- scripts/print_rules.py
- setup.py
> Start 0.2.x

- simplesat/sat/policy.py
> MAINT: remove last DefaultOrderedDict import.

- setup.py
- simplesat/__init__.py
- simplesat/constraints/__init__.py
- simplesat/constraints/kinds.py
- simplesat/constraints/multi.py
- simplesat/constraints/package_parser.py
- simplesat/constraints/parser.py
- simplesat/constraints/requirement.py
- simplesat/constraints/tests/test_multi.py
- simplesat/constraints/tests/test_package_parser.py
- simplesat/constraints/tests/test_parser.py
- simplesat/constraints/tests/test_requirement.py
- simplesat/dependency_solver.py
- simplesat/request.py
- simplesat/requirement.py
- simplesat/rules_generator.py
- simplesat/test_utils.py
- simplesat/tests/test_pool.py
- simplesat/tests/test_requirement.py
- simplesat/tests/test_solver.py
- simplesat/tests/test_test_utils.py
- simplesat/transaction.py
- simplesat/utils/_composer_utils.py
Move the remaining of `enstaller.new_solver` into `simplesat`.
@johntyree
> Move constraints and request into sat

- scripts/index_to_yaml.py
- simplesat/constraints/package_parser.py
- simplesat/constraints/parser.py
- simplesat/constraints/tests/test_package_parser.py
- simplesat/dependency_solver.py
- simplesat/package.py
- simplesat/rules_generator.py
- simplesat/transaction.py
- simplesat/utils/_composer_utils.py
The word "dependency" still appears throughout the code, but only in local contexts where I think it's clear what it means.
> Change PackageMetdata.dependencies to .install_requires

- README.rst
- dev_requirements.txt
- scripts/compare_with_composer.sh
- scripts/solve.py
- simplesat/transaction.py
- simplesat/utils/_composer_utils.py
@johntyree 
I added basic instructions in the `README.rst`. Let me know if that does not work for you.
> BUG: fix composer comparison hack.

- simplesat/constraints/parser.py
- simplesat/constraints/tests/test_requirement.py
> BUG: fix '<name> *' requirement parsing.

- simplesat/dependency_solver.py
- simplesat/errors.py
- simplesat/repository.py
- simplesat/rules_generator.py
> MAINT: always attach requirement to NoPackageError

- simplesat/rules_generator.py
- simplesat/sat/minisat.py
Small refactor.
The `RuleType` is where we should track which types come directly from the user.
> REF: only RuleType knows which members are jobs

- scripts/solve.py
Show the log report if `debug` is nonzero, show it verbosely if `debug > 1`.
> Show log report based on --debug

- simplesat/tests/slow_bokeh_blaze.yaml
This adds the `slow_bokeh_blaze.yaml` Scenario that's currently introduced in #130.
It adds no tests or code, just the scenario. I'm going to merge it here to so that that PR will be less overwhelming.
> TST: add slow scenario for testing

- simplesat/sat/policy/policy_logger.py
Just a small change to the debugging output
> MAINT: fixed width output for debug log

- simplesat/rules_generator.py
- simplesat/tests/test_scenarios_policy.py
- Use the helper func for prettifying a package literal.
- Clean up some bitrotten docstrings
- Clean up error message when scenario unexpectedly succeeds
> Clean up code and small refactor

- scripts/scenario_to_dimacs.py
This script outputs our scenarios in the standard DIMACS format that many other sat solvers can read.
If you have the C++ implementation of minisat available, it can also feed it through there to see what kind of solution it provides.
> Add script to output in DIMACS format.

- docs/Makefile
- docs/source/api.rst
- docs/source/architecture.rst
- docs/source/conf.py
- docs/source/index.rst
- simplesat/constraints/requirement.py
- simplesat/dependency_solver.py
- simplesat/package.py
- simplesat/pool.py
- simplesat/repository.py
- simplesat/request.py
- simplesat/test_utils.py
- simplesat/utils/graph.py
I pretty much just read through the docs for Requests and started to do something similar. It is of course not done yet, I'll just keep making PRs as I get more content written.
We're still waiting on #130 before I start writing about how those are implemented.
> DOCS DOCS DUCS DUCKS DUCKS DUCKS DUCKS 2

- simplesat/dependency_solver.py
- simplesat/tests/test_solver.py
None of these functions care about repositories. They are easier to use and understand if we just pass around the packages themselves.
> REF: work with package iterables, not repositories

- requirements.txt
> MAINT: add enum34 to the normal requirements file

- .travis.yml
- docs/Makefile
- docs/source/api.rst
RTD doesn't seem to tell anyone if it fails.
> REPO: build docs on travis

- dev_requirements.txt
- requirements.txt
- setup.py
We don't need a separate `requirements.txt` anymore. I've also cleaned up our `dev_requirements.txt` and `setup.py`.
> MAINT: cleanup setup.py and remove redundant requirements.txt.

- .gitignore
- MANIFEST.in
- setup.py
- setup_utils.py
- simplesat/__init__.py
This add `__version__` and a few other version-related metadata to the `simplesat` namespace.
This should work for both git repo and sdists.
@noraderam
> Add version

- simplesat/repository.py
- simplesat/tests/test_repository.py
> BUG: fix #185.

- CHANGES.rst
> MAINT: update changelog.

- simplesat/request.py
Using attributes gives us equality comparison
> ENH: Use attributes for Request

- setup.py
- simplesat/constraints/tests/test_package_parser.py
- simplesat/tests/test_repository.py
REF: don't depend on okonomiyaki besides versions.
(cherry picked from commit 109e91287710900a2b57cbb83affc1130a3f7b87)
> Backport #198 to 0.2.x

- docs/source/architecture.rst
- docs/source/sat_solving.rst
- simplesat/sat/policy/undetermined_clause_policy.py
Adapted from discussion on slack.
@noraderam do you think this would have been sufficient?
Example here: https://sat-solver.readthedocs.io/en/develop/sat_solving.html
> Add explanation about the various Requirement types.

- .travis.yml
- simplesat/dependency_solver.py
- simplesat/errors.py
- simplesat/test_utils.py
- simplesat/tests/test_dependency_solver.py
> Function to compute some minimal unsatisfiable subsets

- simplesat/sat/policy/undetermined_clause_policy.py
- simplesat/tests/installed_pkg_missing_in_remote.yaml
- simplesat/tests/installed_pkg_missing_in_remote_not_requested.yaml
- simplesat/tests/test_scenarios_policy.py
Closes #217 
@johntyree I'd love to hear your thoughts on this and the corresponding issue. I believe that this solution is correct.
> FIX: Do not suggest literals without clauses

- CHANGES.rst
Update prior to releasing `0.5.0`
> DOC: update changelog

- simplesat/compute_dependencies.py
- simplesat/pool.py
- simplesat/tests/test_pool.py
Closes #176 
This will simplify something else I'm investigating.
> ENH: Add package and package id iteration to pool

- setup.py
- setup_utils.py
Backport fix to `0.5.x` branch
> MAINT: add support for post release.

- CHANGES.rst
- setup.py
Once this is merged I'll tag 9a25aedafa435fccf248544027c7c04d4078bfab as v0.7.0 and make a new Github release.
> MAINT: Release 0.7.0

- setup.py
Update to latest okonomiyaki and attrs
> MAINT: update runtime dependencies.

- simplesat/dependency_solver.py
- simplesat/request.py
- simplesat/tests/test_solver.py
An upgrade request essentially tries to update every installed package to the latest version, not just the manually marked ones. As for hard updates, it may fail with a satisfiability error, as the latest
version of every package may not give a consistent set.
> FEAT: add new upgrade job.

- .travis.yml
- README.rst
Simple PR to update the travis-ci builds and also check running with the latest okonomiyaki
> Update ci setup

- CHANGES.rst
- README.rst
- setup.py
- Update changelog
- Designate release commit
> Release 0.9.0

- .github/workflows/release.yml
- .github/workflows/run-tests.yml
- setup.cfg
- simplesat/constraints/package_parser.py
- simplesat/constraints/requirement.py
- simplesat/constraints/tests/test_package_parser.py
- simplesat/tests/test_pool.py
- simplesat/tests/test_scenarios_policy.py
- simplesat/utils/tests/test_collections.py
- Run tests on Python 3.12 and fix issues
- Run code lint on Python 3.8
- Update setup.cfg classifiers
fixes #283 
includes #294
> Support cp312
