enthought/sat-solver

simplesat/rules_generator.py, simplesat/tests/simple_numpy_installed_blocking.yaml, simplesat/tests/simple_numpy_installed_blocking_downgrade.yaml, simplesat/tests/simple_numpy_installed_downgrade.yaml, simplesat/tests/simple_numpy_installed_no_upgrade.yaml, simplesat/tests/simple_numpy_installed_upgrade.yaml
We now add rules for installed packages, of the form ` A | B | C | ...` where `A`, `B`, `C`, etc.. are the available versions of installed package `p`.
=> Add installed packages rules

scripts/print_operations.php.in, scripts/print_rules.php.in, scripts/scenario_to_php.py, simplesat/utils/_composer_utils.py
It will be easier to track composer in one package than two.
It also updates the code to work with more recent versions of composer.
=> MAINT: move _composer_utils back to simplesat.

simplesat/dependency_solver.py, simplesat/tests/no_candidate.yaml, simplesat/tests/test_scenarios_policy.py
When the pool cannot provide any packages that satisfy a requirement, we now raise a `egginst.errors.NoPackageFound` exception with a pretty string.
Closes #47
=> Raise error for unsatisfiable requirement

simplesat/dependency_solver.py, simplesat/tests/iris.yaml
This PR implements a simple pruning algorithm to avoid installing packages which end up in the solution but which have no packages that depend on them. It recursively gathers up all of the dependencies of each required package and then does an intersection of those packages with the solution (preserving order).
I think it should be possible to avoid this entirely by being smarter with how backtracking is handled and thereby avoiding this altogether, but that sounds hard and this was very easy.
As a bonus, it revealed that the `iris.yaml` scenario incorrectly includes `zlib` in the expected installed packages, even though no one is asking for it. I have updated the scenario so that tox passes.
=> Prune unnecessary packages from solution

scripts/print_rules.py, simplesat/dependency_solver.py
A remake of #59.
The way pruning was done previously was incorrectly filtering out all packages marked for uninstallation.
This PR simply marks all currently installed packages as also relevant, so that they won't be pruned.
=> Don't prune currently installed packages

scripts/solve.py
It's difficult to validate the behavior of pruning without a way to programmatically disable it. This PR adds a `--no-prune` flag to disable it.
=> ENH: commandline flag for disabling pruning in scripts/solve.py

simplesat/sat/minisat.py, simplesat/sat/policy.py
This just uses the appropriate method on `set` for what we want to do, which is to see if the clause shares any literals with the set of solution literals. I think it's easier to read.
It should also be slightly faster, assuming these are implemented well.
=> MAINT: clarify checks for undetermined clauses

simplesat/tests/common.py, simplesat/tests/numpy_downgrade.yaml, simplesat/tests/test_scenarios_policy.py, simplesat/transaction.py
The `_find_updates` was only considering versions higher than the given package, which prevents `_find_updates` to work with downgrades.
@johntyree @jvkersch
=> BUG: _find_updates should allow lower version to handle downgrades.

simplesat/rules_generator.py, simplesat/tests/preserve_reverse_dependencies.yaml, simplesat/tests/remove_reverse_dependencies.yaml, simplesat/tests/simple_numpy_removed.yaml, simplesat/tests/test_scenarios_policy.py
This PR adds the ability to uninstall packages and their reverse dependencies.
It turns out this was already supported, but for reasons unclear to me extra rules were being generated to force all currently installed packages to remain so. I simply removed the call to create those rules.
Closes #43
=> Support removing packages

simplesat/tests/common.py
The test harness constructs `UpdateOperation` objects backwards.
=> BUG: UpdateOperation constructor args swapped

simplesat/dependency_solver.py
Just a style update. I'm not sure if the `+1` and `-1` was intended to make it easier to read, but I've removed it in favor of signed variables.
This should not introduce any functional changes.
=> MAINT: clarify _solution_to_ids

simplesat/sat/policy.py, simplesat/tests/directly_implied_solution.yaml, simplesat/tests/test_scenarios_policy.py
The original `InstalledFirstPolicy` based on inspecting clauses used to crash if the state of any of the currently installed packages could be directly inferred from the requirements. This PR fixes that by simply filtering those packages out.
As an added bonus, this lets us preserve the `decision_set` across calls, which results in massive speedup. This is now the fastest policy.
Closes #42 and #52.
:sob:
=> BUG: don't crash when decision_set contains assigned lits

simplesat/sat/policy.py, simplesat/tests/test_scenarios_policy.py
I'm not sure how this made it through testing, but `expectedFailure` needs to be imported before we use it :)
=> BUG: fix missing import in test case

scripts/solve.py, simplesat/dependency_solver.py, simplesat/sat/assignment_set.py, simplesat/sat/clause.py, simplesat/sat/policy.py, simplesat/tests/ipython.yaml, simplesat/tests/test_scenarios_policy.py
Adds a `PolicyLogger` class which tracks the suggestions of a Policy and the effect that they have on the assignments. This gives us a crude way to mentally retrace the path that the SAT solver took through the problem. It helps with identifying why particular decisions were made along the way, such as which suggested package forced a particular decision and when.
It should have no effect on the results themselves or the outcome of any testing.
=> Track the search path of the solver

simplesat/dependency_solver.py, simplesat/sat/policy.py, simplesat/tests/test_scenarios_policy.py, simplesat/tests/update_reverse_dependencies.yaml
This PR was extracted from #65. It tries to improve on the `UndeterminedClausePolicy` by computing as little as possible with each request for a new suggested package and then reusing as much of the result as possible.
It does change the behavior slightly, but since the old behavior was quite wrong anyway, I'm not worried about preserving it.
The goal right now is to get this into a usable state. From there we can worry about nuanced behavior.
=> Speed up the UndeterminedClausePolicy

simplesat/test_utils.py, simplesat/tests/preserve_marked.yaml, simplesat/tests/remove_marked_package.yaml, simplesat/tests/simple_numpy_installed_blocking.yaml, simplesat/tests/simple_numpy_installed_blocking_downgrade.yaml, simplesat/tests/test_scenarios_policy.py, simplesat/tests/test_test_utils.py
This is based on #82 
This adds support for a `marked` list to the `Scenario` and a few tests for it.
This helps define explicit what behavior should be. If a package is marked then some version of it *must* remain installed. If it is not marked and not involved in a request, then whether or not the package will be removed is unspecified.
=> Add marked packages to scenarios

scripts/index_to_yaml.py
Have hard-wrapped lines makes it annoying to manipulate the output in an editor. This prevents the wrapping of the lines.
I wasn't sure how to achieve this in a nice way so just used a very large value. If you know how, do tell.
=> ENH: don't wrap long lines in yaml output

simplesat/sat/policy.py, simplesat/sat/tests/test_assignment_set.py
The package_ids we consider come from the Clause literals,
but we look them up in the AssignmentSet. If the
AssignmentSet has never seen that particular id before, it
crashes. This fixes that.
=> BUG: AssignmentSet may not have seen a package_id

simplesat/dependency_solver.py, simplesat/rules_generator.py, simplesat/tests/test_rules_generator.py, simplesat/tests/test_scenarios_policy.py, simplesat/tests/update_all_noop.yaml
Without this check we get stuck in infinite `update-all` loops.
It would probably be nice to refactor this somehow and remove the redundancy, but since the rule generation is currently independent from policy initialization, it won't be a superficial change.
=> BUG: prefer installed packages over remote for same version

requirements.txt, setup.py, simplesat/constraints/package_parser.py, simplesat/constraints/tests/test_package_parser.py, simplesat/package.py, simplesat/pool.py, simplesat/test_utils.py, simplesat/tests/test_pool.py, simplesat/tests/test_repository.py, simplesat/tests/test_solver.py, simplesat/tests/test_test_utils.py
With this PR, `sat-solver` does not depend on `enstaller` anymore.
=> Move package metadata enstaller

simplesat/package.py
The new classes don't have a nice representation, which makes the output of `scripts/solve.py` pretty unreadable. This just implements `__repr__` on those classes in a way similar to the original.
=> Add pretty string for new PackageMetadata

simplesat/constraints/multi.py, simplesat/constraints/parser.py, simplesat/constraints/requirement.py, simplesat/constraints/tests/test_multi.py, simplesat/constraints/tests/test_parser.py, simplesat/constraints/tests/test_requirement.py
This fixes an inconsistency when creating `Requirement` instances in the case of no version constraint. Depending on which ctor we were using, we would get either an empty set (`from_constraints`) or a set with `Any` (`_from_string`).
I also converted our usage from `set`/`frozenset` to `tuple` to keep the list of constraints, to make pretty string representation of `Requirement` more "consistent".
@johntyree
=> Fix requirement inconsistency

simplesat/repository.py, simplesat/tests/test_repository.py
A small addition to `Repository` to allow `package in repository` syntax.
@johntyree
=> FEAT: add support for Repository.__contains__.

scripts/compare_with_composer.sh
This just allows one to pass the other arguments to `script/solve.py` along, such as `--no-prefer-installed`.
=> Pass other args through to solve.py when comparing with composer

scripts/solve.py, simplesat/dependency_solver.py, simplesat/rules_generator.py, simplesat/sat/minisat.py, simplesat/sat/tests/test_minisat.py, simplesat/tests/epd_full_conflict.yaml, simplesat/tests/explicit_conflict.yaml, simplesat/tests/simple_numpy_installed_blocking.yaml, simplesat/tests/simple_numpy_installed_blocking_downgrade.yaml, simplesat/tests/test_rules_generator.py, simplesat/tests/test_scenarios_policy.py, simplesat/tests/update_all_conflict.yaml
This PR improves the `SatisifiabilityError` message significantly.
Our strategy is to dig around in the history trail of the conflicting clauses to find the root requirements, and then do a BFS to find a path of rules from one to the other. The solver's failure implies that all such paths have at least one conflict in them.
The only change in the `RulesGenerator` is that we now keep track of every rule's entire history of requirements. So if we want to install `shapely`, which depends on `numpy` which depends on `MKL`, the rule for installing `MKL` will have attached to it a list containing `numpy`'s dependence on `MKL` and `shapely`'s dependence on `numpy`.
The biggest change is in the `UNSAT` object, which now computes the path between conflicting clauses. It does this using the …
=> Improved error messages on failure.

simplesat/dependency_solver.py, simplesat/test_utils.py, simplesat/tests/test_rules_generator.py
Wasted a bit of time before I realized that most call-sites weren't doing this and my args were ending up in the wrong order.
Someday the world will be on Python 3 and we can pretend this never happened.
=> Use keyword arg syntax when constructing RulesGenerator

simplesat/rules_generator.py, simplesat/sat/clause.py, simplesat/sat/minisat.py, simplesat/tests/epd_full_conflict.yaml, simplesat/tests/explicit_conflict.yaml, simplesat/tests/simple_numpy_installed_blocking.yaml, simplesat/tests/simple_numpy_installed_blocking_downgrade.yaml, simplesat/tests/test_scenarios_policy.py, simplesat/tests/three_way_conflict.yaml, simplesat/tests/update_all_conflict.yaml, simplesat/utils/graph.py
This adds more comments and docstrings to the conflict handling code in UNSAT.
A major change is that the BFS now correctly returns paths that touch *all* of the end_points you give it. Before we simply stopped after the first one and got lucky because we had no tests for conflicts caused by three or more requirements together. We should catch those now and I've added a scenario with a made-up one in it.
This also fixes a non-determinism bug where python2 gives an arbitrary ordering to subclasses of `object`, so calls to `max`, `sorted` etc can differ based on the hash seed.
=> Clean up of error message improvement code

scripts/print_operations.php.in
When they are very long, php doesn't display the whole thing, for whatever reason.
Here I'm just printing it out. It's usually going to be a description of a conflict and might be lengthy.
=> BUG: don't trim long php exception error messages

scripts/index_to_scary_package_strings.py, simplesat/constraints/package_parser.py, simplesat/constraints/parser.py, simplesat/constraints/tests/test_package_parser.py
This tries hard to be more strict about what we accept as a valid distribution name.
I've tested on all the distribution names in the index and was able to round trip them all through a Requirement object successfully.
=> ENH: be stricter about distribution name and version parsing

simplesat/rules_generator.py, simplesat/tests/epd_full_conflict.yaml, simplesat/tests/simple_numpy_installed_blocking.yaml
This fixes a long-standing annoyance with the error reporting. It also enables us to rely on the requirement chain length, which makes it easier to figure out if a particular set of requirements came from a user (because there's only one) or if it was derived by following the dependency graph (because there's more than one).
=> ENH: track package requirements through the work_queue

doc_requirements.txt, simplesat/compute_dependencies.py, simplesat/tests/test_compute_dependencies.py
Closes #171 
`compute_dependencies` will return a set of packages on which packages for a given requirement depend.
`compute_reverse_dependencies` returns a set of packages which the requirement depends on.
Both can return either immediate dependencies or all recursive dependencies via the `transitive` flag.
@cournape, please let me know what you think
=> ENH: Functions to compute dependencies and reverse dependencies

simplesat/tests/preserve_marked_conflict.yaml, simplesat/tests/preserve_marked_conflict_downgrade.yaml, simplesat/tests/test_scenarios_policy.py
This just updates two scenario files' names to reflect their purposes as marked package preservation tests.
=> TST: update scenario name for marked test

simplesat/sat/minisat.py, simplesat/tests/broken_metadata_self_conflict.yaml, simplesat/tests/test_scenarios_policy.py
Fixes #182 
Doesn't handle #183
=> BUG: conflict paths returns  iter of iter of clause

docs/source/api.rst, simplesat/dependency_solver.py, simplesat/tests/test_solver.py
These new API-level functions provide two abilities.
`simplify_requirements` - to turn a large list of package requirements into an equivalent set of smaller requirements for a given suite of packages. It does so by removing all requirements that are captured as dependencies of other requirements. For a self-consistent set of requirements, this will leave us with just the "leaf nodes" of the dependency tree. For requirements that are not self-consistent, the requirements with "mismatched" versions will also be included as they are not captured by any dependencies. This should make this a lossless operation.
`satisfy_requirements` - to use a set of packages to "solve" a requirement. This is the core functionality of this package, wrapped up in small function with an easy to use API. You …
=> ENH: api functions for simplifying and satisfying requests

setup.py, simplesat/constraints/tests/test_package_parser.py, simplesat/tests/test_repository.py
* we remove any usage of okonomiyaki except for `okonomiyaki.versions` (whose API is stable).
* this makes it safe to remove the upper version bound for okonomiyaki dependency
=> REF: don't depend on okonomiyaki besides versions.

simplesat/constraints/package_parser.py, simplesat/constraints/tests/test_package_parser.py, simplesat/dependency_solver.py, simplesat/package.py, simplesat/pool.py, simplesat/rules_generator.py, simplesat/tests/conflict_by_provides.yaml, simplesat/tests/multiple_provides.yaml, simplesat/tests/simple_provides.yaml, simplesat/tests/test_pool.py, simplesat/tests/test_rules_generator.py, simplesat/tests/test_scenarios_policy.py
This adds `PackageMetadata.provides` and the associated code around that. It works by dumping all of the providers of a given name into pool's the internal `name_to_packages` list. The rest of the behavior falls out from that.
If package A `provides` package B, then either A or B can be used to satisfy dependencies (or cause conflicts with) B. This does imply that package A *replaces* package B or that package B is somehow obsolete or that package A should be preferred. With the current implementation, if two packages provide the same thing then you'll get whichever has a higher version number, but this is unspecified. If you care about priority, you'll need to use some of the other metadata features (not yet implemented).
See https://github.com/enthought/sat-solver/issues/177
=> Add "provides" package metadata.

simplesat/constraints/constraint_modifiers.py
Without this, you can't do things like `yaml.dump(modifiers.asdict())` deterministically.
=> BUG: call to asdict must be deterministic

simplesat/constraints/requirement.py, simplesat/constraints/tests/test_requirement.py
As part of the lunch-n-learn, I made this change. I no longer remember why... **BUT** it *does* make the parsing of package names more consistent with the rest of the code both here and elsewhere.
The main change is that this permits a hyphen in between the name and the version and uses the regular expressions written to match the name and version as closely as possible.
For reasons still unknown, we actually had a test before to ensure that package names with a space instead of a hyphen caused errors. Since we don't allow spaces or hyphens in package names, I'm not sure why.
Thoughts on this?
=> BUG: fix package name parsing in requirement

simplesat/constraints/constraint_modifiers.py, simplesat/constraints/tests/test_constraint_modifiers.py, simplesat/request.py
Implements a couple minor improvements discussed previously.
- Validate the `ConstraintModifiers` attribute on `Request
- Add `update` method directly to `ConstraintModifiers`
Also adds a few tests
=> ENH: Request and ConstraintModifiers tweaks

simplesat/dependency_solver.py, simplesat/request.py, simplesat/rules_generator.py, simplesat/sat/policy/undetermined_clause_policy.py, simplesat/test_utils.py, simplesat/tests/complex_numpy_downgrade.yaml, simplesat/tests/no_prefer_installed.yaml, simplesat/tests/simple_update_single.yaml, simplesat/tests/soft_update_with_deps.yaml, simplesat/tests/test_scenarios_policy.py, simplesat/tests/update_reverse_dependencies_no_prefer_installed.yaml, simplesat/tests/update_single.yaml, simplesat/transaction.py
Motivation:
The initial approach for `soft_update` was to remove those packages from the `installed_repository` passed to the `policy`. Reducing the number of knobs on `DependencySolver` to turn can increase our confidence in use of the solver. Instead of editing the `installed_repository` in a somewhat hacky manner we can include all necessary information in the `Request`.
Changes:
- A new job type `soft_update` is added to `Request`. The policy will prefer the installed versions of all packages except those which have `soft_update` jobs. The existing `update` job is renamed to `hard_update`
- Remove policy as attribute for `DependencySolver`. The `policy` needs to be created with the same `pool` and `installed_repository` as the `DependencySolver`. It strikes me as safer to create the …
=> ENH: Optionally ignore installed packages 

simplesat/dependency_solver.py, simplesat/errors.py, simplesat/request.py, simplesat/tests/test_solver.py
This new method uses exactly the same algorithm as solve, but when a satistifiability error occurs, it computes a minimal unsatistiable set of jobs, which helps giving a more human-readable error message.
As an example, let's say we have a small dependency problem with the following packages:
```
mkl_11_3_1 = P(u"mkl 11.3.1-1")
mkl_2017_0_1_1 = P(u"mkl 2017.0.1-1")
mkl_2017_0_1_2 = P(u"mkl 2017.0.1-2")
numpy_1_10_4 = P(u"numpy 1.10.4-1; depends (mkl ^= 11.3.1)")
numpy_1_11_3 = P(u"numpy 1.11.3-1; depends (mkl ^= 2017.0.1)")
scipy_0_17_1 = P(u"scipy 0.17.1-1; depends (mkl ^= 11.3.1, numpy ^= 1.10.4)")
scipy_0_18_1 = P(u"scipy 0.18.1-1; depends (mkl ^= 2017.0.1, numpy ^= 1.11.3)")
```
Then, trying to install both `scipy 0.18.x` and `MKL < 12` cannot work. With solve, the error message is: …
=> FEAT: add new solve_with_hint method.

simplesat/constraints/parser.py, simplesat/constraints/tests/test_package_parser.py
I am not terribly crazy about this fix, but it is the best I have come up with so far. The main issue seems to be that if a package name starts with a number, it is parsed as a `VersionToken`. The difficulty is that we actually want some valid version constraint strings to also be valid package names. This fix just adds a check to ensure the distribution does not actually match the `_DISTRIBUTION_NAME_R` pattern before raising the error.
=> Fix 7z requirement parsing error

simplesat/dependency_solver.py, simplesat/tests/test_solver.py
@itziakos this should fix the issue you were seeing when running packman upgrade-all
=> BUG: fix upgrade_all when no candidate is available for a given installed package

simplesat/dependency_solver.py, simplesat/tests/test_solver.py
BUG: fix upgrade_all when no candidate is available for a given installed package
(cherry picked from commit 0d389942af607ae576137fe65770a58a827c12af)
=> Backport  #26

simplesat/sat/policy/undetermined_clause_policy.py, simplesat/tests/test_solver.py
Fixes #268, by removing the machinery for the `_unsatisfied_clauses` cache. That machinery is broken in two ways:
- the `_unsatisfied_clauses` set isn't ever initialised properly
- the collection of unsatisfied clauses isn't updated when the set of clauses changes (as can happen with the current solver algorithm)
I'd really like to get rid of the changelog too, but we're currently using it for logging purposes.
=> Remove broken _unsatisfied_clauses cache

CHANGES.rst, setup.py, simplesat/constraints/constraint_modifiers.py
The attrs package 19.2.0, which has been released yesterday, deprecates the attribute `convert`. It's basically just renamed to `converter`, so the fix is lightweight. See also
* https://www.attrs.org/en/stable/changelog.html
* https://github.com/python-attrs/attrs/issues/307
* https://github.com/python-attrs/attrs/issues/504
Let me know if I should change anything in this PR.
=> MAINT: Fix deprecated attribute 'convert' to comply with attrs 19.2.0

simplesat/tests/test_transaction.py, simplesat/transaction.py, simplesat/utils/graph.py, simplesat/utils/tests/test_graph.py
- Add support to pass a function to convert package_ids to user friendly strings in toposort.
- Pass a package_id to string function to toposort in the Transaction instance.
- Update tests
=> Better error on cyclic dependencies

.github/workflows/pypi.yml, .github/workflows/release.yml
We add a separate pypi.yml workflow to upload wheels to pypi. The wheels are signed and attestation is generated
=> add pypi publish workflow
